/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Description:": "Description:",
    "Done": "Done",
    "Error loading the Maps API.": "Error loading the Maps API.",
    "Error while retrieving the map information.": "Error while retrieving the map information.",
    "Get a Key": "Get a Key",
    "Hybrid": "Hybrid",
    "Loading…": "Loading…",
    "Map": "Map",
    "Map title shows here  ": "Diverso Geo Map",
    "Only show markers that contain:": "Only show markers that contain:",
    "Please specify a Maps API Key in the Widget Attributes.": "Please specify a Maps API Key in the Widget Attributes.",
    "Read more…": "Read more…",
    "Satellite": "Satellite",
    "The source document could not be processed.": "The source document could not be processed.",
    "Title:": "Title:"
};
